// Mock Admin User
export const mockAdminUser = {
  id: "admin1",
  email: "admin@beautifyinterior.com",
  firstName: "John",
  lastName: "Admin",
  role: "admin",
  permissions: [
    "products.read",
    "products.write",
    "orders.read",
    "orders.write",
    "customers.read",
    "customers.write",
  ],
  isActive: true,
  createdAt: "2024-01-01T00:00:00Z",
  updatedAt: "2024-05-01T00:00:00Z",
  lastLogin: "2024-05-10T10:30:00Z",
};

// Mock data for the admin dashboard

// Mock Categories
export const mockCategories = [
  {
    id: "cat1",
    name: "Furniture",
    slug: "furniture",
    description: "Living room, bedroom, and office furniture",
  },
  {
    id: "cat2",
    name: "Lighting",
    slug: "lighting",
    description: "Lamps, ceiling lights, and outdoor lighting",
  },
  {
    id: "cat3",
    name: "Home Decor",
    slug: "home-decor",
    description: "Decorative items for your home",
  },
  {
    id: "cat4",
    name: "Textiles",
    slug: "textiles",
    description: "Rugs, curtains, and other textile products",
  },
  {
    id: "cat5",
    name: "Kitchen",
    slug: "kitchen",
    description: "Kitchen furniture and accessories",
  },
  {
    id: "cat6",
    name: "Bathroom",
    slug: "bathroom",
    description: "Bathroom furniture and accessories",
  },
];

// Mock Products
export const mockProducts = [
  {
    id: "prod1",
    name: "Modern Velvet Sofa",
    slug: "modern-velvet-sofa",
    sku: "MVS-001",
    price: 74999,
    compareAtPrice: 91999,
    description: "A luxurious velvet sofa with modern design",
    categoryId: "cat1",
    images: ["/placeholder.svg?height=400&width=600"],
    featured: true,
    inStock: true,
    trackQuantity: true,
    quantity: 5,
    lowStockThreshold: 10,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "prod2",
    name: "Minimalist Coffee Table",
    slug: "minimalist-coffee-table",
    sku: "MCT-002",
    price: 29199,
    compareAtPrice: null,
    description: "A sleek minimalist coffee table for your living room",
    categoryId: "cat1",
    images: ["/placeholder.svg?height=400&width=600"],
    featured: false,
    inStock: true,
    trackQuantity: true,
    quantity: 15,
    lowStockThreshold: 5,
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "prod3",
    name: "Pendant Ceiling Light",
    slug: "pendant-ceiling-light",
    sku: "PCL-003",
    price: 10799,
    compareAtPrice: 13299,
    description: "A stylish pendant ceiling light for your dining room",
    categoryId: "cat2",
    images: ["/placeholder.svg?height=400&width=600"],
    featured: true,
    inStock: true,
    trackQuantity: true,
    quantity: 0,
    lowStockThreshold: 5,
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "prod4",
    name: "Decorative Wall Mirror",
    slug: "decorative-wall-mirror",
    sku: "DWM-004",
    price: 7499,
    compareAtPrice: null,
    description: "A beautiful decorative wall mirror to enhance your space",
    categoryId: "cat3",
    images: ["/placeholder.svg?height=400&width=600"],
    featured: false,
    inStock: true,
    trackQuantity: true,
    quantity: 8,
    lowStockThreshold: 10,
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "prod5",
    name: "Handwoven Area Rug",
    slug: "handwoven-area-rug",
    sku: "HAR-005",
    price: 16699,
    compareAtPrice: 20799,
    description: "A handwoven area rug to add warmth to your room",
    categoryId: "cat4",
    images: ["/placeholder.svg?height=400&width=600"],
    featured: true,
    inStock: true,
    trackQuantity: true,
    quantity: 3,
    lowStockThreshold: 5,
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "prod6",
    name: "Marble Kitchen Island",
    slug: "marble-kitchen-island",
    sku: "MKI-006",
    price: 108299,
    compareAtPrice: 124999,
    description: "A luxurious marble kitchen island for your home",
    categoryId: "cat5",
    images: ["/placeholder.svg?height=400&width=600"],
    featured: false,
    inStock: true,
    trackQuantity: false,
    quantity: 0,
    lowStockThreshold: 0,
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "prod7",
    name: "Freestanding Bathtub",
    slug: "freestanding-bathtub",
    sku: "FBT-007",
    price: 74999,
    compareAtPrice: null,
    description: "A modern freestanding bathtub for your bathroom",
    categoryId: "cat6",
    images: ["/placeholder.svg?height=400&width=600"],
    featured: true,
    inStock: true,
    trackQuantity: true,
    quantity: 2,
    lowStockThreshold: 3,
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
];

// Mock Customers
export const mockCustomers = [
  {
    id: "cust1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phone: "555-123-4567",
    totalOrders: 5,
    totalSpent: 103799,
    averageOrderValue: 20759,
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "cust2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phone: "555-987-6543",
    totalOrders: 3,
    totalSpent: 65799,
    averageOrderValue: 21933,
    createdAt: "2024-02-05T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "cust3",
    firstName: "Robert",
    lastName: "Johnson",
    email: "robert.johnson@example.com",
    phone: "555-456-7890",
    totalOrders: 2,
    totalSpent: 29199,
    averageOrderValue: 14599,
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "cust4",
    firstName: "Emily",
    lastName: "Williams",
    email: "emily.williams@example.com",
    phone: "555-789-0123",
    totalOrders: 1,
    totalSpent: 10799,
    averageOrderValue: 10799,
    createdAt: "2024-04-20T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "cust5",
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@example.com",
    phone: "555-321-6547",
    totalOrders: 4,
    totalSpent: 91699,
    averageOrderValue: 22924,
    createdAt: "2024-01-25T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
];

// Mock Orders
export const mockOrders = [
  {
    id: "ord1",
    orderNumber: "ORD-10001",
    customerId: "cust1",
    status: "delivered",
    paymentStatus: "paid",
    shippingMethod: "Standard",
    shippingCost: 829,
    subtotal: 74999,
    tax: 13499,
    total: 89327,
    shippingAddress: {
      firstName: "John",
      lastName: "Doe",
      address1: "123 Main St",
      address2: "Apt 4B",
      city: "New York",
      state: "NY",
      postalCode: "10001",
      country: "USA",
      email: "john.doe@example.com",
      phone: "555-123-4567",
    },
    items: [
      {
        productId: "prod1",
        quantity: 1,
        price: 74999,
        name: "Modern Velvet Sofa",
      },
    ],
    createdAt: "2024-05-01T00:00:00Z",
    updatedAt: "2024-05-05T00:00:00Z",
  },
  {
    id: "ord2",
    orderNumber: "ORD-10002",
    customerId: "cust2",
    status: "shipped",
    paymentStatus: "paid",
    shippingMethod: "Express",
    shippingCost: 1659,
    subtotal: 29199,
    tax: 5255,
    total: 36113,
    shippingAddress: {
      firstName: "Jane",
      lastName: "Smith",
      address1: "456 Oak Ave",
      address2: "",
      city: "Los Angeles",
      state: "CA",
      postalCode: "90001",
      country: "USA",
      email: "jane.smith@example.com",
      phone: "555-987-6543",
    },
    items: [
      {
        productId: "prod2",
        quantity: 1,
        price: 29199,
        name: "Minimalist Coffee Table",
      },
    ],
    createdAt: "2024-05-02T00:00:00Z",
    updatedAt: "2024-05-04T00:00:00Z",
  },
  {
    id: "ord3",
    orderNumber: "ORD-10003",
    customerId: "cust3",
    status: "processing",
    paymentStatus: "paid",
    shippingMethod: "Standard",
    shippingCost: 829,
    subtotal: 10799,
    tax: 1943,
    total: 13571,
    shippingAddress: {
      firstName: "Robert",
      lastName: "Johnson",
      address1: "789 Pine St",
      address2: "",
      city: "Chicago",
      state: "IL",
      postalCode: "60007",
      country: "USA",
      email: "robert.johnson@example.com",
      phone: "555-456-7890",
    },
    items: [
      {
        productId: "prod3",
        quantity: 1,
        price: 10799,
        name: "Pendant Ceiling Light",
      },
    ],
    createdAt: "2024-05-03T00:00:00Z",
    updatedAt: "2024-05-03T00:00:00Z",
  },
  {
    id: "ord4",
    orderNumber: "ORD-10004",
    customerId: "cust4",
    status: "confirmed",
    paymentStatus: "pending",
    shippingMethod: "Standard",
    shippingCost: 829,
    subtotal: 7499,
    tax: 1349,
    total: 9677,
    shippingAddress: {
      firstName: "Emily",
      lastName: "Williams",
      address1: "321 Elm St",
      address2: "Suite 10",
      city: "Houston",
      state: "TX",
      postalCode: "77001",
      country: "USA",
      email: "emily.williams@example.com",
      phone: "555-789-0123",
    },
    items: [
      {
        productId: "prod4",
        quantity: 1,
        price: 7499,
        name: "Decorative Wall Mirror",
      },
    ],
    createdAt: "2024-05-04T00:00:00Z",
    updatedAt: "2024-05-04T00:00:00Z",
  },
  {
    id: "ord5",
    orderNumber: "ORD-10005",
    customerId: "cust5",
    status: "cancelled",
    paymentStatus: "refunded",
    shippingMethod: "Express",
    shippingCost: 1659,
    subtotal: 16699,
    tax: 3005,
    total: 21363,
    shippingAddress: {
      firstName: "Michael",
      lastName: "Brown",
      address1: "654 Maple Ave",
      address2: "",
      city: "Miami",
      state: "FL",
      postalCode: "33101",
      country: "USA",
      email: "michael.brown@example.com",
      phone: "555-321-6547",
    },
    items: [
      {
        productId: "prod5",
        quantity: 1,
        price: 16699,
        name: "Handwoven Area Rug",
      },
    ],
    createdAt: "2024-05-05T00:00:00Z",
    updatedAt: "2024-05-06T00:00:00Z",
  },
];

// Mock Shipping Methods
export const mockShippingMethods = [
  {
    id: "ship1",
    name: "Standard Delivery",
    description: "Regular delivery within 5-7 business days",
    price: 829,
    estimatedDays: 6,
    freeShippingThreshold: 8299,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "ship2",
    name: "Express Delivery",
    description: "Fast delivery within 2-3 business days",
    price: 1659,
    estimatedDays: 2,
    freeShippingThreshold: 16599,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "ship3",
    name: "Overnight Delivery",
    description: "Next business day delivery",
    price: 3319,
    estimatedDays: 1,
    freeShippingThreshold: null,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "ship4",
    name: "Same Day Delivery",
    description: "Delivery within 4-6 hours (select cities only)",
    price: 4979,
    estimatedDays: 0,
    freeShippingThreshold: null,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "ship5",
    name: "Economy Delivery",
    description: "Budget-friendly delivery within 7-10 business days",
    price: 499,
    estimatedDays: 8,
    freeShippingThreshold: 4999,
    isActive: false,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "ship6",
    name: "White Glove Delivery",
    description: "Premium delivery with installation service for furniture",
    price: 8299,
    estimatedDays: 5,
    freeShippingThreshold: 49999,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
];

// Mock Inventory Alerts
export const mockInventoryAlerts = [
  {
    id: "alert1",
    productId: "prod3",
    message: "Pendant Ceiling Light is out of stock",
    severity: "high",
    createdAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "alert2",
    productId: "prod5",
    message: "Handwoven Area Rug is running low (3 remaining)",
    severity: "medium",
    createdAt: "2024-05-02T00:00:00Z",
  },
  {
    id: "alert3",
    productId: "prod7",
    message: "Freestanding Bathtub is running low (2 remaining)",
    severity: "medium",
    createdAt: "2024-05-03T00:00:00Z",
  },
];

// Mock Reviews
export const mockReviews = [
  {
    id: "rev1",
    productId: "prod1",
    customerId: "cust1",
    customerName: "John D.",
    rating: 5,
    title: "Absolutely love this sofa!",
    content:
      "This sofa is not only beautiful but also incredibly comfortable. The velvet fabric is luxurious and the color is exactly as shown in the pictures. Highly recommend!",
    status: "approved",
    isVerified: true,
    createdAt: "2024-04-15T00:00:00Z",
    product: {
      name: "Modern Velvet Sofa",
      sku: "MVS-001",
    },
  },
  {
    id: "rev2",
    productId: "prod2",
    customerId: "cust2",
    customerName: "Jane S.",
    rating: 4,
    title: "Great coffee table",
    content:
      "This coffee table looks great in my living room. The only reason I'm giving it 4 stars instead of 5 is because assembly was a bit challenging.",
    status: "approved",
    isVerified: true,
    createdAt: "2024-04-20T00:00:00Z",
    product: {
      name: "Minimalist Coffee Table",
      sku: "MCT-002",
    },
  },
  {
    id: "rev3",
    productId: "prod3",
    customerId: "cust3",
    customerName: "Robert J.",
    rating: 3,
    title: "Decent light fixture",
    content:
      "The pendant light looks nice but the installation instructions were confusing. Had to hire an electrician to install it properly.",
    status: "pending",
    isVerified: true,
    createdAt: "2024-05-01T00:00:00Z",
    product: {
      name: "Pendant Ceiling Light",
      sku: "PCL-003",
    },
  },
  {
    id: "rev4",
    productId: "prod4",
    customerId: "cust4",
    customerName: "Emily W.",
    rating: 5,
    title: "Beautiful mirror!",
    content:
      "This mirror is absolutely stunning! It makes my entryway look so much more elegant. The quality is excellent and it was easy to hang.",
    status: "pending",
    isVerified: false,
    createdAt: "2024-05-02T00:00:00Z",
    product: {
      name: "Decorative Wall Mirror",
      sku: "DWM-004",
    },
  },
  {
    id: "rev5",
    productId: "prod5",
    customerId: "cust5",
    customerName: "Michael B.",
    rating: 2,
    title: "Not as pictured",
    content:
      "The colors of the rug are much more muted than shown in the product images. Also, it sheds a lot. Disappointed with this purchase.",
    status: "rejected",
    isVerified: true,
    createdAt: "2024-04-25T00:00:00Z",
    product: {
      name: "Handwoven Area Rug",
      sku: "HAR-005",
    },
  },
];
